title: Eldrick's Digital Footprint
email: eldrick.wega@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Eldrick's Digital Footprint. A place where I share my thoughts and theories
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  eldrick19


# Build settings
markdown: kramdown
theme: alembic-jekyll-theme
plugins:
  - jekyll-feed

    

